### ISSUE TITLE
type "twocol" has no rendering definition!

### ISSUE THREAD

**Issue by zzzooorrrx** [SchmidtWebmedia/grid_for_container#4]
Hello,

just upgraded Typo3 v12 to v13 and grid_for_container to 3.0.0

The project is using CEs 2columns [twocol] with grid ratio 66/33
The used grid ratio doesn't change the error message.
I get this message in FE:
ERROR: Content Element with uid "1780" and type "twocol" has no rendering definition!

Any idea how to solve this?

Thank you!

Typo3 13.4.2 (legacy installation)
bootstrap_package 15.0.0
container 3.1.0
grid_for_container 3.0.0
PHP 8.2

**Comment by SchmidtWebmedia** [comment]
Hi, did you add the TypoScript definition of grid-for-container? 
I cannot reproduce this issue.

**Comment by zzzooorrrx** [comment]
Hi,

the simple thing was lost in upgrade process.
That was the right hint.

Thx
